//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRK.MAUI.RefactorKit {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MRK.MAUI.RefactorKit.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detects usage of Command and suggests migration to RelayCommand in MAUI. 
        ///See: https://learn.microsoft.com/en-us/dotnet/communitytoolkit/mvvm/generators/relaycommand.
        /// </summary>
        internal static string CommandAnalyzerDescription {
            get {
                return ResourceManager.GetString("CommandAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command &apos;{0}&apos; should be migrated to RelayCommand.
        /// </summary>
        internal static string CommandAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("CommandAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command usage detected..
        /// </summary>
        internal static string CommandAnalyzerTitle {
            get {
                return ResourceManager.GetString("CommandAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detects usage of DelegateCommand and suggests migration to RelayCommand in MAUI. 
        ///See: https://learn.microsoft.com/en-us/dotnet/communitytoolkit/mvvm/generators/relaycommand.
        /// </summary>
        internal static string DelegateCommandAnalyzerDescription {
            get {
                return ResourceManager.GetString("DelegateCommandAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DelegateCommand &apos;{0}&apos; should be migrated to RelayCommand.
        /// </summary>
        internal static string DelegateCommandAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("DelegateCommandAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DelegateCommand usage detected..
        /// </summary>
        internal static string DelegateCommandAnalyzerTitle {
            get {
                return ResourceManager.GetString("DelegateCommandAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property must follow the new MAUI standard using [ObservableProperty] attribute.
        ///See: https://learn.microsoft.com/en-us/dotnet/communitytoolkit/mvvm/generators/observableproperty.
        /// </summary>
        internal static string PropertyAnalyzerDescription {
            get {
                return ResourceManager.GetString("PropertyAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; need to change the format..
        /// </summary>
        internal static string PropertyAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("PropertyAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property with wrong format found.
        /// </summary>
        internal static string PropertyAnalyzerTitle {
            get {
                return ResourceManager.GetString("PropertyAnalyzerTitle", resourceCulture);
            }
        }
    }
}
